@startuml DiagramaClases

Instituto "1" *--- "0..*" Curso
Instituto "1" *--- "1..*" Contacto
Curso "1" *--- "0..*" Asignatura
Curso  "1" *--- "1" Tutor
Asignatura "0..*" o--- "*" Profesor
Asignatura "0..*" o--- "0..*" Alumno
Asignatura "1" o--- "1" Aula
Aula "1" o--- "0..*" Equipamiento
Alumno "1" o--- "0..*" Nota
Asignatura "1" o--- "0..*" Nota
Persona "1" *--- "1..*" Contacto

Persona <|-- Profesor
Persona <|-- Alumno
Profesor <|-- Tutor
Equipamiento <|-- Mesa
Equipamiento <|-- Silla
Equipamiento <|-- Ordenador
Equipamiento <|-- Proyector


class Persona {
    String nombre
    String apellidos
    datetime fechaNacimiento
    int calcularEdad()
    String nombreCompleto()
    String direccionFormateada()
}
class Contacto {
    String localidad
    String provincia
    String direccion
    Number codigoPostal
    Number telefono
}
class Alumno {
    Bool repetidor
    Bool calcularPasaCurso()
    Number calcularNotaMedia()
    Bool isRepetidor()
}
class Profesor {
    datetime fechaDeContratacion
    Number dineroMes
    Number calcularNotaMedia()
    Number antiguedad()
    Number dineroTotalGanado()
}
class Tutor {
    Number cantidadDeAnyosTutorizando
    Number trieniosDeTutorizacion()
}
class Instituto {
    String nombre
    String codigo
    Number fax
    String web
    String direccionFormateada()
}
class Asignatura {
    String nombre
    Number calcularNotaMediaAlumnos()
    Number totalAprobados()
    Number totalSobresalientes()
    Number totalNotables()
    Number totalAprobados()
    Number totalSuspensos()
    
}
class Curso {
    datetime comienzoDeCurso
    datetime finDeCurso
    String nombre
    Number porcentajeCursoTerminado()
}
class Aula {
    Number capacidadMaxima
    
}
class Nota {
    String nombreTarea
    Enum<tipoTarea> tipoTarea
    Number valorNumerico
    String calcularGradoNota()
}
enum tipoTarea {
  EXAMEN
  ACTIVIDAD
  PRACTICA
}
abstract Equipamiento {
    Number precio
}
class Mesa{
    int capacidad
}
class Silla{
    boolean ruedas
}
Class Proyector{
    String resolucion
    Number lumens 
}
Class Ordenador{
    String cpuname
    Number cpuspeed
    int ram
    int hd
}
@enduml