@startuml DiagramaClases

Instituto "1" *--- "0..*" Curso : cursos >
Instituto "1" *--- "1*" Contacto : info_contacto >
Curso "1" *--- "0..*" Asignatura : asignaturas >
Curso  "1" *--- "1" Tutor : tutor >
Asignatura "0..*" o--- "*" Profesor : profesores >
Asignatura "0..*" o--- "0..*" Alumno : alumnos >
Asignatura "1" o--- "1" Aula : aula >
Aula "1" o--- "0..*" Equipamiento : equipamiento >
Alumno "1" o--- "0..*" Nota : notas >
Asignatura "1" o--- "0..*" Nota : notas >
Persona "1" *--- "1..*" Contacto : infoContactos >

Persona <|-- Profesor
Persona <|-- Alumno
Profesor <|-- Tutor
Equipamiento <|-- Mesa
Equipamiento <|-- Silla
Equipamiento <|-- Ordenador
Equipamiento <|-- Proyector


class Persona {
    String nombre
    String apellidos
    datetime fecha_nacimiento
    int calcular_edad()
    String nombre_completo()
    String direccion_formateada()
}
class Contacto {
    String localidad
    String provincia
    String direccion
    String codigo_postal
    String telefono
}
class Alumno {
    Bool repetidor
    Bool calcular_pasa_curso()
    Number calcular_nota_media()
    Bool isRepetidor()
}
class Profesor {
    datetime fecha_de_contratacion
    Number dinero_mes
    Number calcular_nota_media()
    Number antiguedad()
    Number dinero_total_ganado()
}
class Tutor {
    Number cantidad_anyos_tutorizando
    Number trienios_tutorizacion()
}
class Instituto {
    String id
    String nombre
    String codigo
    String fax
    String web
    String direccion_textual()
}
class Asignatura {
    String nombre
    Number calcular_nota_media_alumnos()
    Number total_aprobados()
    Number total_sobresalientes()
    Number total_notables()
    Number total_aprobados()
    Number total_suspensos()
    
}
class Curso {
    datetime comienzo_de_curso
    datetime fin_de_curso
    String nombre
    Number porcentaje_curso_terminado()
}
class Aula {
    Number capacidad_maxima
    
}
class Nota {
    String nombre_tarea
    Enum<TipoTarea> tipo_tarea
    Number valor_numerico
    String calcular_gradoNota()
}
enum TipoTarea {
  EXAMEN
  ACTIVIDAD
  PRACTICA
}
abstract Equipamiento {
    Number precio
}
class Mesa{
    int capacidad
}
class Silla{
    boolean ruedas
}
Class Proyector{
    String resolucion
    Number lumens 
}
Class Ordenador{
    String cpu_name
    Number cpu_speed
    int ram
    int hd
}
@enduml